# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: feb4cdbc49df8e01959b2aade9ecf8f380016b05ad25eed7b9432520abc2f9d9ca0bf70818b958c24c78516584c620669d9be29b5770927aad4d00f868416240

test:
  secret_key_base: b6694e8796872ed30ee4caf44bd607053ad1501d2bebcdc669bbf4c0cb2cf710b759f3296d3ce46e341f8d20a181a8c6f58cc64d6f1c98ed2e6b17d699430888

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
